name: "Update Snap"

on: [pull_request]
  # push:
  #   branches:
  #     - master
  #   paths-ignore:
  #     - ".github/**"
  #     - "!.github/workflows/push_aur.yml"
  #     - "**.md"
  #     - ".all-contributorsrc"
  #     - ".gitignore"

jobs:
  snap:
    name: "Update Snap"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cpeditor'

    steps:
      - uses: actions/checkout@v2
        #with:
        #  ref: master
        #  fetch-depth: 0

      - name: Update CMake file
        id: update-cmake-file
        run: |
          git fetch --tags
          VERSION=$(git describe --long --tags --abbrev=8 | sed 's/\([^-]*-g\)/r\1/;s/-/./g')
          echo ::set-output name=VERSION::$VERSION
          sed -i "s/project(cpeditor LANGUAGES CXX VERSION .*/project(cpeditor LANGUAGES CXX VERSION $VERSION)/g" CMakeLists.txt
          cat CMakeLists.txt

      - name: Update Snapcraft
        run: |
          cp dist/snap/snapcraft.yaml snapcraft.yaml
          sed -i "/source-/d" snapcraft.yaml
          sed -i "s/source: https.*/source: \."/g snapcraft.yaml
          cat snapcraft.yaml

      - uses: snapcore/action-build@v1
        with:
          snapcraft-args: --enable-experimental-package-repositories 

      - uses: snapcore/action-publish@v1
        with:
          store_login: ${{ secrets.STORE_LOGIN }}
          snap: ${{ steps.build.outputs.snap }}
          release: edge
