name: "Update Snap"

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/push_aur.yml"
      - "**.md"
      - ".all-contributorsrc"
      - ".gitignore"

jobs:
  snap:
    name: "Update Snap"
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cpeditor'

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Update files
        id: update-files
        run: |
          git fetch --tags
          VERSION=$(git describe --long --tags --abbrev=8 | sed 's/\([^-]*-g\)/r\1/;s/-/./g')
          echo ::set-output name=VERSION::$VERSION
          cp dist/aur/git/PKGBUILD cpeditor-git
          cp dist/aur/git/.SRCINFO cpeditor-git
          sed -i "s/@PROJECT_VERSION@/$VERSION/g" cpeditor-git/PKGBUILD cpeditor-git/.SRCINFO

      - name: Publish to AUR
        run: |
          cd cpeditor-git
          git config --global user.email "ashar786khan@gmail.com"
          git config --global user.name "coder3101"
          git diff --quiet HEAD || git commit -am "Update from CI: ${{ steps.update-files.outputs.VERSION }}"
          git push -u origin master
